[workspace]
resolver = "2"
members = [ "pkg/viewer", "pkg/fbgen-rust" ]

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [ ] }

[profile.release]
lto = true
strip = "debuginfo"
opt-level = 3
